# Generated by Django 4.0.3 on 2022-03-28 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writer', '0002_talent_actor_talent_announcer_talent_dancer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='talent',
            old_name='fullName',
            new_name='name',
        ),
    ]
