# Generated by Django 4.0.3 on 2022-03-28 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writer', '0003_rename_fullname_talent_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talent',
            name='photo',
            field=models.ImageField(upload_to='media/talents/images'),
        ),
    ]
