# Generated by Django 4.0.3 on 2022-03-28 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writer', '0004_alter_talent_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talent',
            name='photo',
            field=models.ImageField(upload_to='statics/talents/images'),
        ),
    ]
