# Generated by Django 4.0.3 on 2022-03-29 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writer', '0007_alter_talent_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='email',
            field=models.EmailField(default='', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='talent',
            name='photographer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='talent',
            name='writer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='talent',
            name='phoneNumber',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='photo',
            field=models.ImageField(upload_to='talentsImages'),
        ),
    ]
