# Generated by Django 4.0.3 on 2022-03-29 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writer', '0009_alter_talent_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talent',
            name='phoneNumber',
            field=models.CharField(max_length=12),
        ),
    ]
