# Generated by Django 4.0.3 on 2022-03-29 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writer', '0012_talent_email_alter_talent_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talent',
            name='email',
        ),
    ]
