# Generated by Django 4.0.3 on 2022-03-29 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writer', '0013_remove_talent_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
    ]
